#+title: Dizzybox

A container manager inspired by distrobox.

* Why
Why not.

* Install
Compile dizzybox.c with a C compiler.
Static linking is recommended to be independent of libc.
Optionally, you can symlink the subcommands.

#+begin_src sh
gcc dizzybox.c -o ~/.local/bin/dizzybox -static
ln -s dizzybox ~/.local/bin/dizzybox-enter
ln -s dizzybox ~/.local/bin/dizzybox-create
ln -s dizzybox ~/.local/bin/dizzybox-rm
#+end_src

* Subcommands
** help
Prints out help information; this is not yet very complete.

** enter [CONTAINER] [...COMMAND]
Enters a container. If command is unspecified, it defaults to the shell configured in the container.
chsh can be used in the container to change the shell.

** create [--image IMAGE] [CONTAINER]
Creates the container with the specified image.

** upgrade [CONTAINER]
This can be used to upgrade/reinstall the entrypoint.

** rm [CONTAINER]
Removes the specified container. Currently the same as calling podman rm directly.

* Using Nix for the container
The nixos/nix container image can be used, but nix-daemon must be started manually.
#+begin_src sh
dizzybox enter --image nixos/nix -s nix nix-daemon
#+end_src

nix-env does not work, but you can use nix-shell ex.
#+begin_src sh
dizzybox enter nix nix-shell -p zsh --run zsh
#+end_src

** Export
Currently there's no export, just use shell aliases.

** Differences from distrobox
Distrobox is a much more tested and stable utility.

Dizzybox does not install anything in the container by default, including sudo;
instead, the --su option can be used on entry.

Dizzybox has fewer host dependencies, only requiring podman to use, and a C compiler to build.

Distrobox's main command is a wrapper for subcommands' scripts;
dizzybox uses a monolithic main program which can be symlinked.
